// <auto-generated />
using System.Collections.Generic;
using AgentsAPI.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentsAPI.DataAccess.Migrations
{
    [DbContext(typeof(AgentsDbContext))]
    [Migration("20260127031647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentsAPI.Shared.Models.JobDetail", b =>
                {
                    b.Property<string>("ApplyUrl")
                        .HasColumnType("text");

                    b.Property<List<string>>("Achievements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Compensation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<List<string>>("Requirements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ApplyUrl");

                    b.ToTable("JobDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
