// <auto-generated />
using System;
using AgentsAPI.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentsAPI.DataAccess.Migrations
{
    [DbContext(typeof(AgentsDbContext))]
    partial class AgentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentsAPI.Shared.Models.CrawlerLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CrawlerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("JobsCrawled")
                        .HasColumnType("integer");

                    b.Property<int>("JobsSaved")
                        .HasColumnType("integer");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CrawlerLogs");
                });

            modelBuilder.Entity("AgentsAPI.Shared.Models.CrawlerRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrawlerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CrawlerRuns");
                });

            modelBuilder.Entity("AgentsAPI.Shared.Models.CronCrawler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CrawlerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CronCrawlers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CrawlerName = "Microsoft",
                            CronExpression = "0 0 * * *",
                            IsActive = true,
                            IsRunning = false
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            CrawlerName = "Amazon",
                            CronExpression = "0 0 * * *",
                            IsActive = true,
                            IsRunning = false
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            CrawlerName = "Google",
                            CronExpression = "0 0 * * *",
                            IsActive = true,
                            IsRunning = false
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            CrawlerName = "Fueled",
                            CronExpression = "0 0 * * *",
                            IsActive = true,
                            IsRunning = false
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            CrawlerName = "AshbyHQ",
                            CronExpression = "0 0 1 * *",
                            IsActive = true,
                            IsRunning = false
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000006"),
                            CrawlerName = "Acquia",
                            CronExpression = "0 0 1 * *",
                            IsActive = true,
                            IsRunning = false
                        });
                });

            modelBuilder.Entity("AgentsAPI.Shared.Models.JobDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Achievements")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Compensation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("md5(concat_ws('|', coalesce(\"Title\", ''), coalesce(\"Description\", ''), coalesce(\"ApplyUrl\", '')))", true);

                    b.Property<string>("CrawlerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("JobDetails");
                });

            modelBuilder.Entity("AgentsAPI.Shared.Models.ProcessingJob", b =>
                {
                    b.Property<string>("JobsIds")
                        .HasColumnType("text");

                    b.Property<string>("ApplyUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("JobsIds", "ApplyUrl");

                    b.ToTable("ProcessingJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
